[2024-09-01T12:58:11.595+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-01T12:58:11.739+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline.train_model manual__2024-09-01T12:52:58.348308+00:00 [queued]>
[2024-09-01T12:58:11.750+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline.train_model manual__2024-09-01T12:52:58.348308+00:00 [queued]>
[2024-09-01T12:58:11.752+0000] {taskinstance.py:2856} INFO - Starting attempt 2 of 2
[2024-09-01T12:58:11.768+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): train_model> on 2024-09-01 12:52:58.348308+00:00
[2024-09-01T12:58:11.781+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=341) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-01T12:58:11.782+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'train_model', 'manual__2024-09-01T12:52:58.348308+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmpc_fnjs0n']
[2024-09-01T12:58:11.784+0000] {standard_task_runner.py:72} INFO - Started process 350 to run task
[2024-09-01T12:58:11.785+0000] {standard_task_runner.py:105} INFO - Job 18: Subtask train_model
[2024-09-01T12:58:11.853+0000] {task_command.py:467} INFO - Running <TaskInstance: ml_pipeline.train_model manual__2024-09-01T12:52:58.348308+00:00 [running]> on host bb7792a7b380
[2024-09-01T12:58:12.112+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ml_pipeline' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-09-01T12:52:58.348308+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-01T12:52:58.348308+00:00'
[2024-09-01T12:58:12.113+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-01T12:58:12.114+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-01T12:58:12.115+0000] {logging_mixin.py:190} INFO - Current task name:train_model state:running start_date:2024-09-01 12:58:11.740258+00:00
[2024-09-01T12:58:12.115+0000] {logging_mixin.py:190} INFO - Dag name:ml_pipeline and current dag run status:running
[2024-09-01T12:58:12.116+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-01T12:58:12.117+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ml_pipeline.py", line 24, in train_model
    X = data.drop('target', axis=1)
        ^^^^^^^^^
AttributeError: 'str' object has no attribute 'drop'
[2024-09-01T12:58:12.131+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-01T12:58:12.132+0000] {logging_mixin.py:190} INFO - Task start:2024-09-01 12:58:11.740258+00:00 end:2024-09-01 12:58:12.131009+00:00 duration:0.390751
[2024-09-01T12:58:12.132+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): train_model> dag:<DAG: ml_pipeline> dagrun:<DagRun ml_pipeline @ 2024-09-01 12:52:58.348308+00:00: manual__2024-09-01T12:52:58.348308+00:00, state:running, queued_at: 2024-09-01 12:52:58.384102+00:00. externally triggered: True>
[2024-09-01T12:58:12.133+0000] {logging_mixin.py:190} INFO - Failure caused by 'str' object has no attribute 'drop'
[2024-09-01T12:58:12.133+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=ml_pipeline, task_id=train_model, run_id=manual__2024-09-01T12:52:58.348308+00:00, execution_date=20240901T125258, start_date=20240901T125811, end_date=20240901T125812
[2024-09-01T12:58:12.146+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-01T12:58:12.147+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 18 for task train_model ('str' object has no attribute 'drop'; 350)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ml_pipeline.py", line 24, in train_model
    X = data.drop('target', axis=1)
        ^^^^^^^^^
AttributeError: 'str' object has no attribute 'drop'
[2024-09-01T12:58:12.202+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-09-01T12:58:12.222+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-01T12:58:12.226+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
